pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "ZMusic-Mod"

include("zmusic-core")
include(
        "zmusic-fabric",
        "zmusic-fabric:zmusic-fabric-1.21.10"
)